node_lines:

# Retrieval
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision, retrieval_ndcg, retrieval_map, retrieval_mrr]
      top_k: 10
      modules:
        - module_type: bm25
          bm25_tokenizer: [ko_kiwi, ko_okt, ko_kkma]
        - module_type: vectordb
          embedding_model: [huggingface_bge_m3]
        - module_type: hybrid_rrf
        - module_type: hybrid_cc
          normalize_method: [mm, tmm, z, dbsf]
  nodes:
    - node_type: passage_reranker
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision, retrieval_ndcg, retrieval_map, retrieval_mrr]
        speed_threshold: 10
      top_k: 10
      modules:
        - module_type: pass_reranker
        - module_type: koreranker

- node_line_name: post_retrieve_node_line
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics:
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: huggingface_bge_m3
#          - metric_name: bert_score
#            lang: ko
        generator_modules:
          - module_type: openai_llm
            llm: gpt-4o-mini
      modules:
        - module_type: fstring
          prompt:
          - | 
            단락을 읽고 질문에 답하세요. \n 질문 : {query} \n 단락: {retrieved_contents} \n 답변 :
    - node_type: generator
      strategy:
        metrics: # bert_score 및 g_eval 사용 역시 추천합니다. 빠른 실행을 위해 여기서는 제외하고 하겠습니다.
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: huggingface_bge_m3
      modules:
        - module_type: openai_llm
          llm: gpt-4o
          temperature: 0.6
          batch: 16
        - module_type: openai_llm
          llm: gpt-4o-mini
          temperature: 0.6
          batch: 16