modules:
  - module_type: langchain_parse
    parse_method: [upstagedocumentparse]

# modules:
#   - module_type: langchain_parse
#     parse_method: [pypdf]

# modules:
#   - module_type: llama_index_chunk
#     chunk_method: Token
#     chunk_size: 1024
#     chunk_overlap: 200
#     add_file_name: ko