# RAG 시스템에서 사용할 파라미터를 세팅

vector_store:
  collection_name: "wiki_bgem3"

preprocessor:
  chunk_size: 1024
  chunk_overlap: 200

model:
  embedding_model:
    options:
      - "openai"
      - "bge-m3"
    default: "bge-m3"

  rerank_model:
    options:
      - "BAAI/bge-reranker-v2-m3"
      - "Dongjin-kr/ko-reranker"
    default: "BAAI/bge-reranker-v2-m3"
    # default: "Dongjin-kr/ko-reranker"

retrieval:
  vector_search_top_k: 50
  rerank_top_k: 50

# documents가 있는 폴더 경로
document_directory: "../data"

# summary가 있는 폴더 경로
summarized_document_path: "/home/livin/rag_pipeline/data/sharedoc_text/summarized_text"

# 추론 가속화 device
device: "cuda"


